# ROUTING PANIER 
# REGROUPE L'ENSEMBLE DES ADRESSES ASSOCIE AU BUNDLE PANIER
pa_panier_ajouterannonce:
    path:     /espacemembre/ajouterannonce/{id}
    defaults: { _controller: PAPanierBundle:Panier:ajouterAnnonce }

pa_panier_afficher:
    path:     /espacemembre/monpanier
    defaults: { _controller: PAPanierBundle:Panier:afficherPanier }

