parameters:
#    pa_panier.example.class: PA\PanierBundle\Example

services:
#    pa_panier.example:
#        class: %pa_panier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
