pa_general:
    resource: "@PAGeneralBundle/Resources/config/routing.yml"
    prefix:   /

pa_annonce:
    resource: "@PAAnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce/

pa_panier:
    resource: "@PAPanierBundle/Resources/config/routing.yml"
    prefix:   /panier/

pa_user:
    resource: "@PAUserBundle/Resources/config/routing.yml"
    prefix:   /user/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
