<?php

namespace PA\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
	public function recupannonces()
	{
		$qb = $this->createQueryBuilder('a');
 		$qb
   			->where('a.an_dateSupression IS NULL')
    		->orderBy('a.an_datePublication', 'DESC')
  		;

  		return $qb
   			->getQuery()
    		->getResult()
  		;
	}
}
