<?php

namespace PA\PanierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends EntityRepository
{
	public function recupmonpanier($id)
	{
		$qb = $this->createQueryBuilder('a');
 		$qb
   			->where('a.pauser = :user')
    		->setParameter('user', $id);
  		;

  		return $qb
   			->getQuery()
    		->getSingleResult()
  		;
	}

  public function affichermonpanier($id)
  {
    $qb = $this->createQueryBuilder('p');
    $qb
        
        ->where('p.pauser = :user')
        ->setParameter('user', $id)
      ;

      return $qb
        ->getQuery()
        ->getSingleResult()
      ;
  }
}
