# ROUTING ANNONCE
# REGROUPE L'ENSEMBLE DES ADRESSES ASSOCIE AU BUNDLE ANNONCE
pa_annonce_homepage:
    path:     /chose/{name}
    defaults: { _controller: PAAnnonceBundle:Annonce:index }

pa_annonce_ajouter:
    path:     /espacemembre/creer
    defaults: { _controller: PAAnnonceBundle:Annonce:creerAnnonce }

pa_annonce_secteur:
    path:     /choixdepartement
    defaults: { _controller: PAAnnonceBundle:Annonce:affSecteur }

pa_annonce_ajoutercategorie:
    path:     /admin/creercategorie
    defaults: { _controller: PAAnnonceBundle:Categorie:creerCategorie }

pa_annonce_afficher_offre:
    path:     /offres
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherAnnoncesOffre }

pa_annonce_afficher_demande:
    path:     /demandes
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherAnnoncesDemande }