# ROUTING ANNONCE
# REGROUPE L'ENSEMBLE DES ADRESSES ASSOCIE AU BUNDLE ANNONCE
pa_annonce_homepage:
    path:     /chose/{name}
    defaults: { _controller: PAAnnonceBundle:Annonce:index }

pa_annonce_ajouter:
    path:     /espacemembre/creer
    defaults: { _controller: PAAnnonceBundle:Annonce:creerAnnonce }

pa_annonce_modifier:
    path:     /espacemembre/modifier/{id}
    defaults: { _controller: PAAnnonceBundle:Annonce:modifierAnnonce }

pa_annonce_secteur:
    path:     /choixdepartement
    defaults: { _controller: PAAnnonceBundle:Annonce:affSecteur }

pa_annonce_ajoutercategorie:
    path:     /admin/creercategorie
    defaults: { _controller: PAAnnonceBundle:Categorie:creerCategorie }

pa_annonce_afficher_offre:
    path:     /offres
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherAnnoncesOffre }

pa_annonce_afficher_demande:
    path:     /demandes
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherAnnoncesDemande }

pa_annonce_afficher_mesannonces:
    path:     /espacemembre/mes-annonces
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherMesAnnonces }

pa_annonce_detail_annonce:
    path:     /AMODIFIER
    defaults: { _controller: PAAnnonceBundle:Annonce:afficherDetailAnnonce }

afficher_resultat_annonce:
    path:  /resultat/{page}
    defaults: { _controller: PAAnnonceBundle:Annonce:rechercherAnnonce, page: 1 }