parameters:
#    pa_annonce.example.class: PA\AnnonceBundle\Example

services:
#    pa_annonce.example:
#        class: %pa_annonce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
