pa_general_accueil:
    path:     /
    defaults: { _controller: PAGeneralBundle:Default:afficherIndex }


pa_general_offres:
    path:     /offres/
    defaults: { _controller: PAGeneralBundle:Default:afficherOffres }


pa_general_demandes:
    path:     /demandes/
    defaults: { _controller: PAGeneralBundle:Default:afficherDemandes }


pa_general_mes_annonces:
    path:     /mes-annonces/
    defaults: { _controller: PAGeneralBundle:Default:afficherMesAnnonces }


pa_general_mon_compte:
    path:     /mon-compte/
    defaults: { _controller: PAGeneralBundle:Default:afficherMonCompte }


pa_general_mon_panier:
    path:     /mon-panier/
    defaults: { _controller: PAGeneralBundle:Default:afficherPanier }


pa_general_contact:
    path:     /contact/
    defaults: { _controller: PAGeneralBundle:Default:afficherContact }


pa_general_mentions:
    path:     /mentions-legales/
    defaults: { _controller: PAGeneralBundle:Default:afficherMentions }


pa_general_liens:
    path:     /liens/
    defaults: { _controller: PAGeneralBundle:Default:afficheLiens }


pa_general_connexion:
    path:     /connexion/
    defaults: { _controller: PAGeneralBundle:Default:connexion }


pa_general_inscription:
    path:     /inscription/
    defaults: { _controller: PAGeneralBundle:Default:afficheInscription }


pa_general_deconnexion:
    path:     /deconnexion/
    defaults: { _controller: PAGeneralBundle:Default:deconnexion }


pa_general_interface:
    path:     /admin/interfaceGestion/
    defaults: { _controller: PAGeneralBundle:Default:afficheInterface }