parameters:
    pa_general.twig.pa_general_extension: PA\GeneralBundle\Twig\PAExtension

# src/PA/GeneralBundle/Resources/config/services.yml
services:
    pa_general.twig.pa_general_extension:
        class: PA\GeneralBundle\Twig\PAExtension
        tags:
            - { name: twig.extension }